
apiVersion: v1
kind: Pod
metadata:
  name: redis-rmi
  labels:
    purpose: redis-rmi
    app: redis-rmi
spec:
  containers:
    - name: redis-rmi
      image: redis:latest
      imagePullPolicy: IfNotPresent
      ports:
       - containerPort: 6379 #exposed container port and protocol
